# Generated by Django 5.2.9 on 2025-12-28 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Debtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المديون")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رقم الجوال"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
            ],
            options={
                "verbose_name": "مديون",
                "verbose_name_plural": "المديونون",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="يمكن أن يكون باركود أو كود يدوي",
                        max_length=50,
                        unique=True,
                        verbose_name="كود المنتج",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المنتج")),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر التكلفة"
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر البيع"
                    ),
                ),
                (
                    "current_stock",
                    models.IntegerField(default=0, verbose_name="الكمية في المخزون"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="منتج نشط"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "منتج",
                "verbose_name_plural": "المنتجات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ ووقت البيع"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "كاش"),
                            ("transfer", "حوالة"),
                            ("debt", "دين"),
                        ],
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="إجمالي الفاتورة"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم الذي سجّل العملية",
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        blank=True,
                        help_text="مطلوب فقط في حالة الدفع بالدين",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.debtor",
                        verbose_name="المديون",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة بيع",
                "verbose_name_plural": "فواتير المبيعات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="الكمية")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="سعر الوحدة وقت البيع",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="إجمالي السطر"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.sale",
                        verbose_name="الفاتورة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صنف في الفاتورة",
                "verbose_name_plural": "أصناف الفواتير",
            },
        ),
    ]
