# Generated by Django 5.2.9 on 2025-12-28 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="debtor",
            field=models.ForeignKey(
                blank=True,
                help_text="مطلوب فقط في حالة الدفع بالدين",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="store.debtor",
                verbose_name="المديون",
            ),
        ),
        migrations.CreateModel(
            name="DebtPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ المسدّد"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "كاش"), ("transfer", "حوالة")],
                        max_length=20,
                        verbose_name="طريقة السداد",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="ملاحظة"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ ووقت السداد"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم الذي سجّل السداد",
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="store.debtor",
                        verbose_name="المديون",
                    ),
                ),
            ],
            options={
                "verbose_name": "سداد دين",
                "verbose_name_plural": "سدادات الديون",
                "ordering": ["-paid_at"],
            },
        ),
    ]
